name: Deploy to Vercel (Development)

on:
  push:
    branches-ignore:
      - main  # Ignora a branch main, executa para todas as outras branches

jobs:
  deploy:
    name: Deploy to Vercel (Development)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.11  # Altere para a versão necessária
        cache: 'npm'

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Build Project
      run: npm run build

    - name: Deploy to Vercel (Development)
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Seu Vercel token
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}  # O ID do projeto Vercel
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}  # O ID da organização Vercel
        NODE_ENV: development
      run: |
        npx vercel --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID --project $VERCEL_PROJECT_ID --env NODE_ENV=development --yes