name: Deploy to Vercel (Development)

on:
  push:
    branches-ignore:
      - main  # Ignora a branch main, executa para todas as outras branches

jobs:
  deploy:
    name: Deploy to Vercel (Development)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.11  # Altere para a versão necessária
        cache: 'npm'

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Build Project
      run: npm run build

    - name: Deploy to Vercel (Development)
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        npx vercel --yes --scope ${{ secrets.VERCEL_SCOPE }} --env NODE_ENV=development
        
    - name: Debug Output
      run: |
        echo "Escopo: ${{ secrets.VERCEL_SCOPE }}"
        echo "NODE_ENV: ${{ secrets.NODE_ENV }}"
        npx vercel --yes --scope ${{ secrets.VERCEL_SCOPE }} --env NODE_ENV=development